// MACROS IS TO DECREASE THE SIZE OF THE CODE AND ALOS EASY READABILITY
#ifndef  DEFINES_H
#define  DEFINES_H
// >>>>>>>>>>>>>>>>>>>>>>>>.........................
#define SETBIT(WORD,BIT) (WORD|=1<<BIT)  ///--TO SET THE BIT TO 1
#define CLRBIT(WORD,BIT) (WORD&=~(1<<BIT)) // ---TO CLEAR PARTICULAR BIT
#define READBIT(WORD,BIT) ((WORD>>BIT)&1) // BIT STATUS
#define CPLBIT(WORD,BITPOS) (WORD^=(1<<BITPOS)) // TOGGLE OR COMPLIMENT BIT
#define WRITEBIT(WORD,BITPOS,BITLEVEL) \
(BITLEVEL?(WORD|=1<<BITPOS):(WORD&=~(1<<BITPOS))) // WRITING ONE BIT DATA TO ANOTHER PIN

// READING BIT AND WRITING SAME BIT TO THE ANOTHER BIT
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)\
        (DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT)))
// WRITNG TO THE BYTE WITHOUT AFFECTING THE OTHER BITS
/*#define WRITEBYTE(WORD,BITSTARTPOS,BYTE)\
        (WORD=(WORD&~(0xFF<<BITSTARTPOS))|(BYTE<<BITSTARTPOS))*/
#define WRITEBYTE(WORD, BITSTARTPOS, BYTE) \
    do { \
        WORD = (WORD & ~(0xFFUL << (BITSTARTPOS))) | ((BYTE & 0xFFUL) << (BITSTARTPOS)); \
    } while (0)
// NIBBLE RELATED MACROS
#define WRITENIBBLE(WORD,NIBPOS,NIBBLE)\
         (WORD=(WORD&~(0xF << (NIBPOS)))|(NIBBLE<<NIBPOS))

#define READNIBBLE(WORD,NIBPOS)  ((WORD>>NIBPOS)&(0xF))

#endif
