#ifndef  LCD_DEFINES_H
#define  LCD_DEFINES_H
// HERE THE MODES OF OPERATIONS ARE DEFINED AS THE MACROS RATHER WRITING DIRECTLY PREFERING THIS WAY IS BETTER OPTION
//>>>>>
#define CLEAR_LCD          0x01
#define RET_CUR_HOME       0x02
#define SHIFT_CUR_RIGHT    0x06
#define SHIFT_CUR_LEFT     0x07
#define DISP_OFF           0x08
#define DISP_ON_CUR_OFF    0x0C
#define DISP_ON_CUR_ON     0x0E
#define DISP_ON_CUR_BLINK  0x0F
#define SHIFT_DISP_RIGHT   0x14
#define SHIFT_DISP_LEFT    0x10
#define MODE_8BIT_1LINE    0x30
#define MODE_8BIT_2LINE    0x38
#define GOTO_LINE1_POS0    0x80
#define GOTO_LINE2_POS0    0xC0
//// CGRAM COMMAND 
#define GOTO_CGRAM_START    0x40

#endif
